#!/bin/bash
#
# Delete current backups
#
if [[ -d "/srv/database/backups" ]]; then
    for BACKUP in $(find /srv/database/backups/ -maxdepth 1 -name "*.sql"); do
        echo "removing ${BACKUP}"
        rm $BACKUP;
    done
fi