#!/bin/bash


echo "Cleaning the virtual machine's /etc/hosts file..."
sed -n '/# vagrant-auto$/!p' /etc/hosts > /tmp/hosts
sudo mv /tmp/hosts /etc/hosts
echo "Adding domains to the virtual machine's /etc/hosts file..."
find /var/www/ -maxdepth 5 -name 'hosts-init' | \
while read hostfile; do
  while IFS='' read -r line || [ -n "$line" ]; do
    if [[ "#" != ${line:0:1} ]]; then
      if [[ -z "$(grep -q "^127.0.0.1 $line$" /etc/hosts)" ]]; then
        echo "127.0.0.1 $line # vagrant-auto" >> "/etc/hosts"
        echo " * Added $line from $hostfile"
      fi
    fi
  done < "$hostfile"
done
