#!/bin/bash
echo "###########################"
echo "running custom setup script"
echo "###########################"

for SITE_CONFIG_FILE in $(find /var/www -maxdepth 5 -name 'init.sh'); do
# Look for site setup scripts
  DIR="$(dirname "$SITE_CONFIG_FILE")"
  (
  echo "$DIR"
  cd "$DIR"
  source init.sh
  )
done
