#!/bin/bash

USER="root"
PASSWORD="root"

echo 'removing databases'
if [[ -d "/srv/databases" ]]; then
    for BACKUP in $(find /srv/databases -maxdepth 1 -name "*.sql"); do
        echo "removing ${BACKUP}"
        rm $BACKUP;
    done
fi


DATABASES=`mysql -u $USER -p$PASSWORD -e "SHOW DATABASES;" | tr -d "| " | grep -v Database`
for db in $DATABASES; do
    if [[ "$db" != "sys" ]] && [[ "$db" != "information_schema" ]] && [[ "$db" != "performance_schema" ]] && [[ "$db" != "mysql" ]] && [[ "$db" != _* ]] ; then
        echo "Dumping database: $db"
        echo mysqldump -u $USER -p$PASSWORD --databases $db > /srv/databases/$db.sql
        mysqldump -u $USER -p$PASSWORD --databases $db > /srv/databases/$db.sql
    fi
done